spring:
  mysql:
    jdbcUrl: ${mysql_url}
    username: ${mysql_username}
    password: ${mysql_password}
    dialect: org.hibernate.dialect.MySQLDialect
  db2:
    jdbcUrl: ${db2_url}
    username: ${db2_username}
    password: ${db2_password}
    dialect: org.hibernate.dialect.DB2400Dialect
    schema: ${db2_schema}
    
logging.level.org.hibernate.SQL: DEBUG