spring:
  datasource:
    username: ${database_username}
    password: ${database_password}
    url: ${database_url}
  jpa:
    show-sql: true
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQLDialect
        format_sql: true